/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: 'us-east-2',
  aws_cognito_identity_pool_id:
    'us-east-2:270be10f-5b76-409c-b31c-47d257fff534',
  aws_cognito_region: 'us-east-2',
  aws_user_pools_id: 'us-east-2_K3Dw55OjO',
  aws_user_pools_web_client_id: '6fvos5qud1vhsvi2njlb76heer',
  oauth: {},
  aws_cognito_username_attributes: [],
  aws_cognito_social_providers: [],
  aws_cognito_signup_attributes: ['EMAIL'],
  aws_cognito_mfa_configuration: 'OFF',
  aws_cognito_mfa_types: ['SMS'],
  aws_cognito_password_protection_settings: {
    passwordPolicyMinLength: 8,
    passwordPolicyCharacters: [],
  },
  aws_cognito_verification_mechanisms: ['EMAIL'],
  aws_appsync_graphqlEndpoint:
    'https://ipz6gtx33ba4jiwejj4kklvenu.appsync-api.us-east-2.amazonaws.com/graphql',
  aws_appsync_region: 'us-east-2',
  aws_appsync_authenticationType: 'API_KEY',
  aws_appsync_apiKey: 'da2-25yonimjsbg6fptta33re5lm3e',
  aws_user_files_s3_bucket: 'dynamicresumes05635-staging',
  aws_user_files_s3_bucket_region: 'us-east-2',
};

export default awsmobile;
